// Utility functions
export const daysUntilDeadline = (deadline) => {
  if (deadline === 'Ongoing') return 9999
  const today = new Date()
  const deadlineDate = new Date(deadline)
  const diff = deadlineDate - today
  return Math.ceil(diff / (1000 * 60 * 60 * 24))
}

// Grant data array
export const allGrants = [
  {
    id: 1,
    name: 'National Wildlife Federation Grant Program',
    organization: 'National Wildlife Federation',
    orgDescription: 'Leading conservation organization dedicated to protecting wildlife and habitats.',
    amount: 500000,
    deadline: '2026-08-15',
    focus: 'Wildlife Conservation & Habitat Protection',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Supports organizations working to protect native wildlife and their habitats. Grants fund research, habitat restoration, and public education initiatives.',
    keyRequirements: [
      '501(c)(3) non-profit status required',
      'Focus on native species conservation',
      'Matching funds preferred (25%)',
      'Detailed project timeline and impact metrics',
    ],
    eligibility: [
      'Registered 501(c)(3) non-profit organizations',
      'Minimum 2 years of conservation work',
      'Active board of directors',
      'Audited financial statements available',
    ],
    applicationSteps: [
      'Submit preliminary proposal (2-3 pages)',
      'If approved, submit full application with budget',
      'Participate in phone interview',
      'Award decision made within 60 days',
    ],
    priority: 'high',
    applicationsPerYear: 3,
  },
  {
    id: 2,
    name: 'Disney Conservation Fund',
    organization: 'Walt Disney Company',
    orgDescription: 'Supports conservation efforts that protect wildlife and habitats globally.',
    amount: 250000,
    deadline: '2026-07-30',
    focus: 'Species Recovery & Habitat Conservation',
    animalTypes: ['Reptiles', 'Mixed Species'],
    description: 'Provides grants for wildlife conservation projects with emphasis on species recovery and habitat protection. Focuses on innovative approaches and community engagement.',
    keyRequirements: [
      'Non-profit organization status',
      'Project budget less than $500,000',
      'Conservation focus with measurable outcomes',
      'Community engagement component',
    ],
    eligibility: [
      '501(c)(3) status or equivalent',
      'Active conservation work in specified region',
      'Commitment to long-term monitoring',
      'Partnership with academic or government agencies',
    ],
    applicationSteps: [
      'Submit online application',
      'Provide project budget and timeline',
      'Letters of support from partners',
      'Review period: 8-12 weeks',
    ],
    priority: 'high',
    applicationsPerYear: 2,
  },
  {
    id: 3,
    name: 'Reptile Conservation Grant (IRCF)',
    organization: 'International Reptile Conservation Foundation',
    orgDescription: 'Dedicated specifically to reptile and amphibian conservation worldwide.',
    amount: 100000,
    deadline: '2026-09-30',
    focus: 'Reptile & Amphibian Conservation',
    animalTypes: ['Reptiles', 'Amphibians'],
    description: 'Supports field research, captive breeding programs, and habitat restoration for threatened reptile species. Strong emphasis on species-specific work.',
    keyRequirements: [
      'Reptile conservation expertise demonstrated',
      'Clear conservation goal with timeline',
      'Budget under $50,000 preferred',
      'Annual progress reports required',
    ],
    eligibility: [
      'Non-profit organizations',
      'Academic institutions with research programs',
      'Zoos and sanctuaries with conservation missions',
      'International applications welcome',
    ],
    applicationSteps: [
      'Submit project proposal (5 pages max)',
      'Include detailed budget breakdown',
      'Provide CVs of key personnel',
      'Decision within 90 days',
    ],
    priority: 'high',
    applicationsPerYear: 2,
  },
  {
    id: 4,
    name: 'Petco Love Foundation Animal Welfare Grants',
    organization: 'Petco Love Foundation',
    orgDescription: 'Focuses on improving the health and lives of companion and shelter animals.',
    amount: 50000,
    deadline: '2026-08-31',
    focus: 'Animal Welfare & Rescue',
    animalTypes: ['Small Mammals', 'Mixed Species'],
    description: 'Funds programs that enhance animal welfare, develop community capacity for animal care, and support innovation in shelter operations and rescue services.',
    keyRequirements: [
      'Direct animal welfare focus',
      'Community benefit component',
      'Nonprofit status required',
      'Project must be completable in 12 months',
    ],
    eligibility: [
      '501(c)(3) animal-focused organizations',
      'Existing animal care programs',
      'Board-governed organization',
      'No geographic restrictions',
    ],
    applicationSteps: [
      'Online application via Petco website',
      'Provide project details and budget',
      'Letter of support from leadership',
      'Rolling review: decisions within 30 days',
    ],
    priority: 'medium',
    applicationsPerYear: 4,
  },
  {
    id: 5,
    name: 'Bristol Myers Squibb Foundation Patient Advocate Program',
    organization: 'Bristol Myers Squibb Foundation',
    orgDescription: 'Foundation supporting patient access, education, and advocacy programs.',
    amount: 300000,
    deadline: '2026-07-15',
    focus: 'Medical Research & Health Education',
    animalTypes: ['Mixed Species'],
    description: 'Supports organizations working on disease research, patient education, and community health initiatives. Can include research facilities caring for disease-study animals.',
    keyRequirements: [
      'Health or research focus',
      'Direct patient/animal care component',
      'Evidence-based programs',
      'Measurable outcomes documented',
    ],
    eligibility: [
      '501(c)(3) organizations',
      'Academic medical centers',
      'Research institutions',
      'Community health organizations',
    ],
    applicationSteps: [
      'Complete detailed application',
      'Provide program outcomes data',
      'Budget narrative required',
      'Site visit may be conducted',
    ],
    priority: 'medium',
    applicationsPerYear: 2,
  },
  {
    id: 6,
    name: 'American Forests Grant Program',
    organization: 'American Forests',
    orgDescription: 'Nation\'s oldest forest conservation organization.',
    amount: 150000,
    deadline: '2026-10-15',
    focus: 'Habitat Restoration & Forest Conservation',
    animalTypes: ['Reptiles', 'Amphibians', 'Birds', 'Mixed Species'],
    description: 'Grants support forest restoration, tree planting, and habitat protection for wildlife dependent on forest ecosystems.',
    keyRequirements: [
      'Conservation project in forest ecosystem',
      'Long-term stewardship plan',
      'Community engagement component',
      'Matching funds or in-kind support',
    ],
    eligibility: [
      'Non-profit organizations',
      'Government agencies',
      'Educational institutions',
      'Tribal governments',
    ],
    applicationSteps: [
      'Submit brief proposal',
      'Site information and location map',
      'Letters of support from partners',
      'Review period: 60-90 days',
    ],
    priority: 'medium',
    applicationsPerYear: 3,
  },
  {
    id: 7,
    name: 'National Science Foundation Research Grants',
    organization: 'National Science Foundation',
    orgDescription: 'U.S. government agency supporting science, technology, and engineering research.',
    amount: 1000000,
    deadline: '2026-11-01',
    focus: 'Scientific Research & Education',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Highly competitive research grants for study of animal behavior, ecology, evolution, and conservation. Requires research component and academic partnership.',
    keyRequirements: [
      'Original research proposal',
      'Academic or research institution partnership',
      'Detailed research methodology',
      'Statistical analysis plan required',
    ],
    eligibility: [
      'Universities and research institutions',
      'Non-profits with research capacity',
      'Qualified researchers with PhDs',
      'Must have research track record',
    ],
    applicationSteps: [
      'Preliminary proposal review',
      'Full proposal submission if invited',
      'Peer scientific review',
      'Final decision within 6-8 months',
    ],
    priority: 'low',
    applicationsPerYear: 4,
  },
  {
    id: 8,
    name: 'Gordon and Betty Moore Foundation Conservation',
    organization: 'Gordon and Betty Moore Foundation',
    orgDescription: 'Provides grants to tackle environmental challenges and protect natural resources.',
    amount: 750000,
    deadline: '2026-09-20',
    focus: 'Environmental Conservation & Climate Action',
    animalTypes: ['Mixed Species', 'Reptiles'],
    description: 'Supports conservation organizations addressing climate change, habitat loss, and species extinction. Looking for innovative, scalable solutions.',
    keyRequirements: [
      'Demonstrable conservation impact',
      'Innovation in conservation approach',
      'Potential for replication and scaling',
      'Strong leadership and partnerships',
    ],
    eligibility: [
      '501(c)(3) conservation organizations',
      'International organizations',
      'Research institutions',
      'Collaboration across organizations encouraged',
    ],
    applicationSteps: [
      'Letter of inquiry (2-3 pages)',
      'If invited, full proposal submission',
      'Significant grants require site visit',
      'Decision timeline: 4-6 months',
    ],
    priority: 'high',
    applicationsPerYear: 1,
  },
  {
    id: 9,
    name: 'Audubon Conservation Partnership Fund',
    organization: 'Audubon Society',
    orgDescription: 'Works to protect birds, other wildlife, and their habitats.',
    amount: 200000,
    deadline: '2026-08-10',
    focus: 'Wildlife & Habitat Protection',
    animalTypes: ['Birds', 'Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Supports partnerships between Audubon and other organizations to protect critical habitats and species. Multi-year funding available.',
    keyRequirements: [
      'Partnership with Audubon chapter or program',
      'Species/habitat protection focus',
      'Community engagement element',
      'Measurable conservation outcomes',
    ],
    eligibility: [
      'Non-profit organizations',
      'Educational institutions',
      'Government agencies',
      'Willingness to partner with Audubon',
    ],
    applicationSteps: [
      'Pre-application discussion with Audubon',
      'Submission of formal proposal',
      'Partnership agreement finalization',
      'Funding decision within 60 days',
    ],
    priority: 'high',
    applicationsPerYear: 2,
  },
  {
    id: 10,
    name: 'Humane Society International Wildlife Grants',
    organization: 'Humane Society International',
    orgDescription: 'Focused on preventing animal cruelty and promoting animal protection worldwide.',
    amount: 175000,
    deadline: '2026-10-01',
    focus: 'Animal Welfare & Species Protection',
    animalTypes: ['Reptiles', 'Mixed Species', 'Primates'],
    description: 'Funds projects addressing wildlife trafficking, habitat protection, and animal welfare. Global focus with emphasis on innovative solutions.',
    keyRequirements: [
      'Clear animal welfare focus',
      'Demonstrable impact on animal protection',
      'Organizational capacity demonstrated',
      'Detailed outcome metrics',
    ],
    eligibility: [
      'Non-profit organizations',
      'International organizations',
      'Academic institutions',
      'Government agencies with animal protection missions',
    ],
    applicationSteps: [
      'Submit detailed project proposal',
      'Budget and timeline documentation',
      'Organizational background materials',
      'Response within 90 days',
    ],
    priority: 'medium',
    applicationsPerYear: 2,
  },
  {
    id: 11,
    name: 'Christensen Fund Conservation Grants',
    organization: 'The Christensen Fund',
    orgDescription: 'Supports indigenous peoples and local communities leading conservation.',
    amount: 350000,
    deadline: '2026-09-15',
    focus: 'Community-Based Conservation',
    animalTypes: ['Reptiles', 'Mixed Species'],
    description: 'Funds conservation initiatives led by indigenous peoples and local communities. Emphasis on traditional knowledge and sustainable practices.',
    keyRequirements: [
      'Community-led or community-benefiting project',
      'Sustainable livelihood component',
      'Long-term conservation strategy',
      'Local capacity building',
    ],
    eligibility: [
      'Community organizations',
      'Indigenous peoples groups',
      'Local non-profits',
      'Capacity to manage conservation land or resources',
    ],
    applicationSteps: [
      'Letter of interest submission',
      'Community meetings and consultation required',
      'Full proposal if invited',
      'Multi-round review process',
    ],
    priority: 'low',
    applicationsPerYear: 1,
  },
  {
    id: 12,
    name: 'Bayer Crop Science Community Grant Program',
    organization: 'Bayer Company',
    orgDescription: 'Corporate foundation supporting agricultural and environmental education.',
    amount: 100000,
    deadline: '2026-08-01',
    focus: 'Environmental Education & Sustainability',
    animalTypes: ['Mixed Species', 'Amphibians'],
    description: 'Supports science education, environmental stewardship, and habitat preservation. Strong focus on STEM education.',
    keyRequirements: [
      'Education component required',
      'Science focus (STEM preferred)',
      'Community benefit clear',
      'Measurable educational outcomes',
    ],
    eligibility: [
      'Non-profit organizations',
      'Schools and educational institutions',
      'Community centers',
      'Environmental education programs',
    ],
    applicationSteps: [
      'Online grant application',
      'Project narrative and budget',
      'Letters of support',
      'Decision within 45 days',
    ],
    priority: 'medium',
    applicationsPerYear: 2,
  },
  {
    id: 13,
    name: 'Packard Foundation Species Conservation',
    organization: 'David and Lucile Packard Foundation',
    orgDescription: 'Funds conservation, education, and science initiatives.',
    amount: 1500000,
    deadline: '2026-12-15',
    focus: 'Species Conservation & Ecosystem Protection',
    animalTypes: ['Reptiles', 'Amphibians', 'Birds', 'Mixed Species'],
    description: 'Large-scale funding for innovative species conservation approaches. Multi-year grants available. Strategic focus on threatened species.',
    keyRequirements: [
      'Significant conservation impact potential',
      'Multi-year strategic plan',
      'Partnership network',
      'Research and action integration',
    ],
    eligibility: [
      'Non-profit conservation organizations',
      'Research institutions',
      'International organizations',
      'Government agencies with conservation focus',
    ],
    applicationSteps: [
      'Pre-proposal discussion encouraged',
      'Request for proposal if strategic fit',
      'Comprehensive proposal submission',
      'Review period: 4-6 months minimum',
    ],
    priority: 'low',
    applicationsPerYear: 1,
  },
  {
    id: 14,
    name: 'American Zoo and Aquarium Association Conservation Fund',
    organization: 'American Alliance of Museums',
    orgDescription: 'Supports conservation work by zoos, aquariums, and sanctuaries.',
    amount: 75000,
    deadline: '2026-09-01',
    focus: 'Zoo-Based Conservation & Education',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Funds conservation projects at AZA-accredited facilities including field conservation, research, and community education.',
    keyRequirements: [
      'AZA accreditation required',
      'Research or field conservation component',
      'Species conservation focus',
      'Education/outreach element',
    ],
    eligibility: [
      'AZA-accredited facilities',
      'Zoos, aquariums, sanctuaries',
      'Member institutions in good standing',
      'Demonstrated conservation commitment',
    ],
    applicationSteps: [
      'Submit through AZA member portal',
      'Detailed project description',
      'Budget and timeline',
      'Peer review: 60 days',
    ],
    priority: 'high',
    applicationsPerYear: 1,
  },
  {
    id: 15,
    name: 'Walton Family Foundation Conservation',
    organization: 'Walton Family Foundation',
    orgDescription: 'Major funder of conservation and natural resource management.',
    amount: 2000000,
    deadline: '2026-11-30',
    focus: 'Natural Resource Management & Conservation',
    animalTypes: ['Mixed Species', 'Reptiles'],
    description: 'Supports large-scale conservation initiatives. Focus on scalable solutions and partnerships. Multi-year funding available.',
    keyRequirements: [
      'Significant conservation impact',
      'Scalability and replicability',
      'Strong partnerships',
      'Measurement and evaluation capacity',
    ],
    eligibility: [
      'Established conservation organizations',
      'Non-profits with track record',
      'Research institutions',
      'Collaborative initiatives',
    ],
    applicationSteps: [
      'Invitation to propose typically required',
      'Comprehensive strategic proposal',
      'Financial documentation required',
      'Extended review process',
    ],
    priority: 'low',
    applicationsPerYear: 1,
  },
  {
    id: 16,
    name: 'Defenders of Wildlife Wildlife Habitat Fund',
    organization: 'Defenders of Wildlife',
    orgDescription: 'Dedicated to protecting and restoring wildlife and habitats.',
    amount: 250000,
    deadline: '2026-08-20',
    focus: 'Habitat Protection & Wildlife Defense',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Supports habitat protection, species defense, and wildlife corridor development. Emphasis on reducing human-wildlife conflict.',
    keyRequirements: [
      'Wildlife and habitat focus',
      'Conflict reduction or habitat protection component',
      'Community engagement strategy',
      'Measurable conservation outcomes',
    ],
    eligibility: [
      'Non-profit organizations',
      'Government agencies',
      'Educational institutions',
      'Community organizations',
    ],
    applicationSteps: [
      'Letter of intent submission',
      'Full proposal if invited',
      'Project timeline and budget detail',
      'Decision within 90 days',
    ],
    priority: 'high',
    applicationsPerYear: 2,
  },
  {
    id: 17,
    name: 'TNC (The Nature Conservancy) Partnership Fund',
    organization: 'The Nature Conservancy',
    orgDescription: 'Global conservation organization protecting lands and waters.',
    amount: 500000,
    deadline: '2026-10-31',
    focus: 'Land and Water Conservation',
    animalTypes: ['Reptiles', 'Amphibians', 'Birds', 'Mixed Species'],
    description: 'Funds conservation projects in partnership with TNC. Focus on ecosystem-based conservation and species protection.',
    keyRequirements: [
      'Partnership with TNC',
      'Ecosystem-scale approach',
      'Long-term conservation strategy',
      'Adaptive management plan',
    ],
    eligibility: [
      'Non-profits',
      'Government agencies',
      'Educational institutions',
      'Willingness to work with TNC',
    ],
    applicationSteps: [
      'TNC partnership discussion',
      'Joint proposal development',
      'Submitted as collaborative proposal',
      'TNC manages review process',
    ],
    priority: 'medium',
    applicationsPerYear: 2,
  },
  {
    id: 18,
    name: 'Wildlife Education and Research Foundation (WERF)',
    organization: 'WERF',
    orgDescription: 'Funds wildlife education and research projects globally.',
    amount: 125000,
    deadline: '2026-09-10',
    focus: 'Wildlife Education & Research',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Supports field research and education programs focusing on understudied species and ecosystems. Particularly interested in emerging conservation leaders.',
    keyRequirements: [
      'Research and/or education focus',
      'Field work component',
      'Understudied species or region',
      'Budget under $50,000 preferred',
    ],
    eligibility: [
      'Non-profit organizations',
      'Academic institutions',
      'Emerging conservation leaders',
      'International applicants welcome',
    ],
    applicationSteps: [
      'Online application form',
      'Research proposal or education plan',
      'Budget and timeline',
      'Decision within 60 days',
    ],
    priority: 'medium',
    applicationsPerYear: 3,
  },
  {
    id: 19,
    name: 'San Diego Zoo Wildlife Alliance Conservation',
    organization: 'San Diego Zoo Wildlife Alliance',
    orgDescription: 'Global leader in zoo-based conservation and wildlife care.',
    amount: 300000,
    deadline: '2026-09-30',
    focus: 'Species Recovery & Habitat Conservation',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Funds field conservation, species recovery programs, and facility improvements. Emphasis on science-based approaches.',
    keyRequirements: [
      'Field conservation or breeding program',
      'Species recovery focus',
      'Research component',
      'Partnership potential with SDZWA',
    ],
    eligibility: [
      'Non-profit organizations',
      'Zoos and sanctuaries',
      'Research institutions',
      'International organizations',
    ],
    applicationSteps: [
      'Submit project proposal',
      'Detailed budget',
      'Timeline and conservation metrics',
      'Review period: 90 days',
    ],
    priority: 'high',
    applicationsPerYear: 2,
  },
  {
    id: 20,
    name: 'PetSmart Charities Animal Welfare Grants',
    organization: 'PetSmart Charities',
    orgDescription: 'Supports animal welfare and rescue organizations nationwide.',
    amount: 50000,
    deadline: '2026-07-31',
    focus: 'Animal Welfare & Rescue',
    animalTypes: ['Small Mammals', 'Mixed Species'],
    description: 'Funds programs that help homeless, abused, and at-risk animals. Emphasis on shelter improvement and adoption services.',
    keyRequirements: [
      'Direct animal welfare focus',
      'Shelter or rescue organization',
      'Community benefit clear',
      'Innovation in animal care',
    ],
    eligibility: [
      '501(c)(3) animal welfare organizations',
      'Shelters and rescue organizations',
      'Community animal care programs',
      'No size restrictions',
    ],
    applicationSteps: [
      'Online application via website',
      'Organization and program information',
      'Budget and impact metrics',
      'Rolling review: decisions within 30 days',
    ],
    priority: 'medium',
    applicationsPerYear: 4,
  },
  {
    id: 21,
    name: 'Wildlife Research & Conservation Endowment (WRCE)',
    organization: 'WRCE',
    orgDescription: 'Dedicated to funding wildlife research and conservation science.',
    amount: 200000,
    deadline: '2026-10-15',
    focus: 'Wildlife Research & Science',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Supports research that advances conservation science and wildlife management. Focus on applied research with conservation implications.',
    keyRequirements: [
      'Research project with wildlife focus',
      'Conservation application of findings',
      'Academic or research partnership',
      'Peer-reviewed publication plan',
    ],
    eligibility: [
      'Universities and research institutions',
      'Non-profits with research capacity',
      'Qualified principal investigators',
      'Institutional support required',
    ],
    applicationSteps: [
      'Submit research proposal',
      'Methodology and research timeline',
      'Publication plan',
      'Peer review process: 120 days',
    ],
    priority: 'medium',
    applicationsPerYear: 2,
  },
  {
    id: 22,
    name: 'Environmental Excellence Foundation Grants',
    organization: 'Environmental Excellence Foundation',
    orgDescription: 'Funds environmental protection and sustainability initiatives.',
    amount: 175000,
    deadline: '2026-11-01',
    focus: 'Environmental Protection & Sustainability',
    animalTypes: ['Mixed Species', 'Reptiles'],
    description: 'Supports environmental programs with demonstrated community impact. Focus on innovative, replicable solutions.',
    keyRequirements: [
      'Environmental protection focus',
      'Community engagement and benefit',
      'Innovation and scalability',
      'Measurable environmental outcomes',
    ],
    eligibility: [
      'Non-profit organizations',
      'Community organizations',
      'Educational institutions',
      'Government agencies',
    ],
    applicationSteps: [
      'Letter of inquiry',
      'Full application if invited',
      'Program details and budget',
      'Decision within 60 days',
    ],
    priority: 'low',
    applicationsPerYear: 2,
  },
  {
    id: 23,
    name: 'National Geographic Big Cats Initiative',
    organization: 'National Geographic Society',
    orgDescription: 'Supports conservation projects discovered through National Geographic.',
    amount: 400000,
    deadline: '2026-12-01',
    focus: 'Species-Specific Conservation',
    animalTypes: ['Primates', 'Large Mammals'],
    description: 'Funds wildlife conservation projects featured in National Geographic. Multi-year funding for high-impact work.',
    keyRequirements: [
      'Compelling conservation story',
      'Charismatic species or ecosystem focus',
      'Documentary potential',
      'Strong field team',
    ],
    eligibility: [
      'Non-profit organizations',
      'Research institutions',
      'International organizations',
      'Adventurous conservation leaders',
    ],
    applicationSteps: [
      'Submit project outline',
      'Compelling narrative and visuals',
      'Field team credentials',
      'Opportunity for site visit and documentation',
    ],
    priority: 'low',
    applicationsPerYear: 1,
  },
  {
    id: 24,
    name: 'Robert Wood Johnson Foundation Health Equity Grants',
    organization: 'Robert Wood Johnson Foundation',
    orgDescription: 'Major foundation focused on improving health and health equity.',
    amount: 300000,
    deadline: '2026-10-01',
    focus: 'Health & Community Wellbeing',
    animalTypes: ['Mixed Species'],
    description: 'Funds health-related programs with conservation or animal care components. Focus on health equity and community benefit.',
    keyRequirements: [
      'Health equity focus',
      'Community benefit clear',
      'Sustainable program design',
      'Evaluation and measurement plan',
    ],
    eligibility: [
      '501(c)(3) organizations',
      'Community health organizations',
      'Educational institutions',
      'Health-related non-profits',
    ],
    applicationSteps: [
      'Submit LOI first',
      'Full proposal if encouraged',
      'Detailed budget and evaluation plan',
      'Decision within 90 days',
    ],
    priority: 'low',
    applicationsPerYear: 2,
  },
  {
    id: 25,
    name: 'Bank of America Philanthropic Foundation',
    organization: 'Bank of America',
    orgDescription: 'Corporate foundation supporting community development and environmental stewardship.',
    amount: 150000,
    deadline: '2026-08-15',
    focus: 'Community & Environmental Stewardship',
    animalTypes: ['Mixed Species', 'Reptiles'],
    description: 'Supports non-profits addressing community needs and environmental challenges. Preference for organizations in communities where BofA operates.',
    keyRequirements: [
      'Community-focused organization',
      'Clear social or environmental benefit',
      'Operating in BofA service area',
      'Financial stability demonstrated',
    ],
    eligibility: [
      '501(c)(3) non-profits',
      'Community organizations',
      'Located in BofA service areas',
      'Audited financials required',
    ],
    applicationSteps: [
      'Online application',
      'Organizational overview',
      'Program and budget details',
      'Decision within 60 days',
    ],
    priority: 'medium',
    applicationsPerYear: 3,
  },
  {
    id: 26,
    name: 'Johnson & Johnson Foundation Animal Care Program',
    organization: 'Johnson & Johnson Foundation',
    orgDescription: 'Corporate foundation supporting health and community programs.',
    amount: 100000,
    deadline: '2026-09-15',
    focus: 'Animal Care & Research',
    animalTypes: ['Mixed Species', 'Reptiles'],
    description: 'Funds animal care programs and research facilities. Emphasis on improving care standards and animal welfare research.',
    keyRequirements: [
      'Animal care facility or program',
      'Welfare improvement focus',
      'Research component preferred',
      'Innovation in care standards',
    ],
    eligibility: [
      'Non-profit organizations',
      'Research institutions',
      'Zoos and sanctuaries',
      'Academically affiliated programs',
    ],
    applicationSteps: [
      'Submit detailed proposal',
      'Facility information and credentials',
      'Budget and innovation plan',
      'Review period: 75 days',
    ],
    priority: 'medium',
    applicationsPerYear: 2,
  },
  {
    id: 27,
    name: 'Google.org Ecosystem Fund',
    organization: 'Google.org',
    orgDescription: 'Google\'s nonprofit organization focusing on addressing global challenges.',
    amount: 500000,
    deadline: '2026-11-15',
    focus: 'Technology for Conservation',
    animalTypes: ['Mixed Species', 'Reptiles'],
    description: 'Supports use of technology and data science for conservation. Strong emphasis on innovation and scalability.',
    keyRequirements: [
      'Technology or data science component',
      'Conservation application',
      'Scalable model',
      'Measurable impact potential',
    ],
    eligibility: [
      'Non-profit organizations',
      'Social enterprises',
      'Research institutions',
      'Innovation-focused organizations',
    ],
    applicationSteps: [
      'Invitation to propose (typically)',
      'Or submit LOI outlining innovation',
      'Full proposal if selected',
      'Extended evaluation period',
    ],
    priority: 'low',
    applicationsPerYear: 1,
  },
  {
    id: 28,
    name: 'Berkley Wildlife Conservation Trust',
    organization: 'Berkley Wildlife Conservation Trust',
    orgDescription: 'Focuses on wildlife conservation across multiple continents.',
    amount: 225000,
    deadline: '2026-10-20',
    focus: 'Global Wildlife Conservation',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Supports conservation work with potential for global impact. Multi-year grants available for proven organizations.',
    keyRequirements: [
      'Global conservation perspective',
      'Scalable solutions',
      'Partnership network',
      'Long-term vision',
    ],
    eligibility: [
      'Non-profit conservation organizations',
      'Research institutions',
      'International organizations',
      'Established track record preferred',
    ],
    applicationSteps: [
      'Submit comprehensive proposal',
      'Global impact potential documentation',
      'Partnership agreements',
      'Review period: 100+ days',
    ],
    priority: 'medium',
    applicationsPerYear: 1,
  },
  {
    id: 29,
    name: 'Zoological Society of San Diego - Research Fund',
    organization: 'Zoological Society of San Diego',
    orgDescription: 'Zoo-based organization supporting research and conservation.',
    amount: 100000,
    deadline: '2026-09-01',
    focus: 'Zoo-Based Research & Conservation',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Supports research by zoo professionals and partners. Focus on applied conservation and animal care advancement.',
    keyRequirements: [
      'Research or care advancement project',
      'Zoo partnership or affiliation',
      'Applied conservation focus',
      'Peer-reviewed publication plan',
    ],
    eligibility: [
      'Zoo professionals',
      'Research institutions partnering with zoos',
      'Zoo-affiliated organizations',
      'Academia partnering with zoos',
    ],
    applicationSteps: [
      'Submit research proposal',
      'Detailed methodology',
      'Budget and timeline',
      'Peer review: 60 days',
    ],
    priority: 'high',
    applicationsPerYear: 2,
  },
  {
    id: 30,
    name: 'Trust for Public Land Community Engagement',
    organization: 'Trust for Public Land',
    orgDescription: 'Creates parks and green space for everyone, especially underserved communities.',
    amount: 175000,
    deadline: '2026-08-30',
    focus: 'Park & Green Space Development',
    animalTypes: ['Mixed Species'],
    description: 'Funds habitat restoration and wildlife areas within parks. Community benefit and access requirements.',
    keyRequirements: [
      'Public space and habitat development',
      'Community access and benefit',
      'Equity focus',
      'Long-term management plan',
    ],
    eligibility: [
      'Non-profit organizations',
      'Government agencies',
      'Community groups',
      'Parks and recreation organizations',
    ],
    applicationSteps: [
      'Letter of intent',
      'Project details and community plan',
      'Budget and timeline',
      'Decision within 60 days',
    ],
    priority: 'low',
    applicationsPerYear: 2,
  },
  {
    id: 31,
    name: 'Wildlife Land Trust Habitat Protection',
    organization: 'Wildlife Land Trust',
    orgDescription: 'Protects wildlife habitat through land conservation.',
    amount: 250000,
    deadline: '2026-11-10',
    focus: 'Habitat Land Protection',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Funds land acquisition, conservation easements, and habitat management. Long-term conservation focus.',
    keyRequirements: [
      'Land-based conservation project',
      'Wildlife habitat focus',
      'Long-term management plan',
      'Baseline habitat assessment',
    ],
    eligibility: [
      'Land trusts',
      'Non-profit conservation organizations',
      'Government agencies',
      'Private landowners (in partnerships)',
    ],
    applicationSteps: [
      'Detailed land and project description',
      'Conservation plan',
      'Budget and timeline',
      'Site visit conducted',
    ],
    priority: 'medium',
    applicationsPerYear: 1,
  },
  {
    id: 32,
    name: 'Amphibian Ark Captive Breeding Fund',
    organization: 'Amphibian Ark',
    orgDescription: 'Dedicated to amphibian conservation through captive breeding programs.',
    amount: 75000,
    deadline: '2026-09-20',
    focus: 'Amphibian Captive Breeding',
    animalTypes: ['Amphibians'],
    description: 'Funds amphibian breeding facilities and programs for threatened species. Support for husbandry research and reintroduction planning.',
    keyRequirements: [
      'Amphibian breeding program',
      'Endangered species focus',
      'Reintroduction plan',
      'Scientific protocols and record-keeping',
    ],
    eligibility: [
      'Zoos and sanctuaries',
      'Research institutions',
      'Non-profits with breeding capacity',
      'Experienced amphibian programs',
    ],
    applicationSteps: [
      'Submit program details',
      'Breeding protocols and facility info',
      'Species and reintroduction plans',
      'Decision within 75 days',
    ],
    priority: 'high',
    applicationsPerYear: 2,
  },
  {
    id: 33,
    name: 'Exotic Reptile Conservation Foundation',
    organization: 'ERCF',
    orgDescription: 'Specifically focused on conservation of exotic reptile species.',
    amount: 90000,
    deadline: '2026-08-25',
    focus: 'Exotic Reptile Conservation',
    animalTypes: ['Reptiles'],
    description: 'Supports breeding, research, and field conservation of exotic reptiles. Multi-year funding available for established programs.',
    keyRequirements: [
      'Exotic reptile focus',
      'Breeding or field conservation',
      'Scientific approach',
      'Community education component',
    ],
    eligibility: [
      'Herpetological societies',
      'Zoos and sanctuaries',
      'Research institutions',
      'Hobbyist groups with breeding programs',
    ],
    applicationSteps: [
      'Detailed program description',
      'Species information and conservation status',
      'Budget breakdown',
      'Decision within 60 days',
    ],
    priority: 'high',
    applicationsPerYear: 2,
  },
  {
    id: 34,
    name: 'National Science Foundation STEM Education',
    organization: 'National Science Foundation',
    orgDescription: 'Federal agency supporting STEM education and research.',
    amount: 400000,
    deadline: '2026-11-15',
    focus: 'STEM & Science Education',
    animalTypes: ['Reptiles', 'Mixed Species'],
    description: 'Funds science education programs with wildlife or conservation focus. Strong emphasis on student engagement and equity.',
    keyRequirements: [
      'Science education focus',
      'Student engagement and outcomes',
      'Equity and inclusion',
      'Evaluation and assessment plan',
    ],
    eligibility: [
      'Educational institutions',
      'Non-profit organizations',
      'Research centers',
      'Science museums and centers',
    ],
    applicationSteps: [
      'Proposal through FastLane system',
      'Detailed education plan',
      'Student recruitment and retention strategy',
      'Peer review: 120+ days',
    ],
    priority: 'low',
    applicationsPerYear: 2,
  },
  {
    id: 35,
    name: 'Heising-Simons Foundation Conservation',
    organization: 'Heising-Simons Foundation',
    orgDescription: 'Supports climate and environmental conservation initiatives.',
    amount: 600000,
    deadline: '2026-12-01',
    focus: 'Climate & Environmental Conservation',
    animalTypes: ['Mixed Species', 'Reptiles'],
    description: 'Large grants for conservation addressing climate change. Multi-year strategic initiatives preferred.',
    keyRequirements: [
      'Climate-related conservation focus',
      'Strategic impact potential',
      'Scalability',
      'Strong partnerships',
    ],
    eligibility: [
      'Conservation non-profits',
      'Research institutions',
      'International organizations',
      'Collaborative initiatives',
    ],
    applicationSteps: [
      'Letter of inquiry',
      'Strategic proposal if invited',
      'Detailed budget and impact analysis',
      'Extended review process',
    ],
    priority: 'low',
    applicationsPerYear: 1,
  },
  {
    id: 36,
    name: 'World Wildlife Fund Conservation Grants',
    organization: 'World Wildlife Fund',
    orgDescription: 'Global conservation organization protecting wildlife and ecosystems.',
    amount: 350000,
    deadline: '2026-10-15',
    focus: 'Global Wildlife & Ecosystem Conservation',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Supports field conservation projects addressing habitat loss and species decline. Partnership-based approach.',
    keyRequirements: [
      'Field conservation project',
      'Measurable conservation outcomes',
      'Partnership network',
      'Long-term strategy',
    ],
    eligibility: [
      'Non-profit organizations',
      'Research institutions',
      'International organizations',
      'Government agencies',
    ],
    applicationSteps: [
      'Concept note submission',
      'Full proposal if invited',
      'Site visit may be conducted',
      'Decision within 6-8 weeks',
    ],
    priority: 'high',
    applicationsPerYear: 1,
  },
  {
    id: 37,
    name: 'The Elephant Fund Conservation',
    organization: 'The Elephant Fund',
    orgDescription: 'Focuses on protecting elephants and their habitats globally.',
    amount: 200000,
    deadline: '2026-09-30',
    focus: 'Megafauna Conservation',
    animalTypes: ['Large Mammals'],
    description: 'Supports conservation of large mammals including elephants. Emphasis on human-wildlife coexistence.',
    keyRequirements: [
      'Large mammal conservation focus',
      'Conflict mitigation component',
      'Community engagement',
      'Measurable outcomes',
    ],
    eligibility: [
      'Non-profit organizations',
      'Research institutions',
      'Community-based organizations',
      'International organizations',
    ],
    applicationSteps: [
      'Submit project proposal',
      'Community consultation documentation',
      'Budget and timeline',
      'Decision within 90 days',
    ],
    priority: 'medium',
    applicationsPerYear: 2,
  },
  {
    id: 38,
    name: 'Marine Conservation Institute',
    organization: 'Marine Conservation Institute',
    orgDescription: 'Protects marine ecosystems and species through science-based conservation.',
    amount: 275000,
    deadline: '2026-11-20',
    focus: 'Marine & Aquatic Conservation',
    animalTypes: ['Reptiles', 'Amphibians'],
    description: 'Funds marine and aquatic ecosystem conservation. Includes freshwater habitats with amphibians.',
    keyRequirements: [
      'Aquatic or marine focus',
      'Ecosystem-based approach',
      'Science-based planning',
      'Policy or protection component',
    ],
    eligibility: [
      'Non-profit organizations',
      'Research institutions',
      'Government agencies',
      'International organizations',
    ],
    applicationSteps: [
      'LOI submission',
      'Full proposal if invited',
      'Scientific documentation',
      'Collaborative approach valued',
    ],
    priority: 'low',
    applicationsPerYear: 1,
  },
  {
    id: 39,
    name: 'Community Foundation Local Giving',
    organization: 'Community Foundations Network',
    orgDescription: 'Local and regional community foundations supporting local causes.',
    amount: 50000,
    deadline: '2026-08-31',
    focus: 'Local Community Benefit',
    animalTypes: ['Mixed Species'],
    description: 'Regional community foundation grants. Typically local focus with flexible priorities. Smaller grants with less competition.',
    keyRequirements: [
      'Local organizational focus',
      'Community benefit clear',
      'Location alignment',
      'Financial stability',
    ],
    eligibility: [
      '501(c)(3) local non-profits',
      'Community organizations',
      'Educational institutions',
      'Operating within fund service area',
    ],
    applicationSteps: [
      'Community foundation application',
      'Program and budget details',
      'Local impact documentation',
      'Decision typically within 60 days',
    ],
    priority: 'medium',
    applicationsPerYear: 4,
  },
  {
    id: 40,
    name: 'Tropical Forest Initiative Fund',
    organization: 'Tropical Forest Initiative',
    orgDescription: 'Supports conservation of tropical forests and their wildlife.',
    amount: 300000,
    deadline: '2026-10-01',
    focus: 'Tropical Ecosystem Conservation',
    animalTypes: ['Reptiles', 'Amphibians', 'Primates', 'Mixed Species'],
    description: 'Funds tropical ecosystem protection and wildlife conservation. International focus with emphasis on threatened regions.',
    keyRequirements: [
      'Tropical ecosystem focus',
      'Wildlife protection component',
      'Local community benefit',
      'Research and action integration',
    ],
    eligibility: [
      'Non-profit organizations',
      'International organizations',
      'Research institutions',
      'Local conservation groups',
    ],
    applicationSteps: [
      'Detailed project proposal',
      'Regional and species information',
      'Community engagement documentation',
      'Review period: 90-120 days',
    ],
    priority: 'medium',
    applicationsPerYear: 1,
  },
  {
    id: 41,
    name: 'Darwin Initiative - UK Government',
    organization: 'Darwin Initiative (UK)',
    orgDescription: 'UK government funding for conservation in developing countries.',
    amount: 150000,
    deadline: '2026-09-01',
    focus: 'Biodiversity Conservation in Developing Nations',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Supports conservation in countries rich in biodiversity. Focus on partnership between UK and developing countries.',
    keyRequirements: [
      'Project in eligible developing country',
      'UK partner organization required',
      'Biodiversity conservation focus',
      'Community benefit and capacity building',
    ],
    eligibility: [
      'Registered charities (UK)',
      'Non-profits in developing countries',
      'Educational institutions',
      'Research organizations',
    ],
    applicationSteps: [
      'Expression of interest',
      'Full application if invited',
      'Partnership documentation required',
      'Multi-stage review process',
    ],
    priority: 'low',
    applicationsPerYear: 1,
  },
  {
    id: 42,
    name: 'Private Family Foundations (Donor Network)',
    organization: 'Various Family Offices',
    orgDescription: 'Network of private family foundations with conservation interests.',
    amount: 100000,
    deadline: 'Ongoing',
    focus: 'Donor-Specific Interests',
    animalTypes: ['Reptiles', 'Mixed Species'],
    description: 'Direct funding opportunities through private family offices. Personalized giving with ongoing relationship-building.',
    keyRequirements: [
      'Alignment with donor values',
      'Personal relationship potential',
      'Regular reporting and updates',
      'Flexibility and responsiveness',
    ],
    eligibility: [
      'Non-profit organizations',
      'Established track record helpful',
      'Compelling story and impact',
      'Personal connection valued',
    ],
    applicationSteps: [
      'Introduction through network',
      'Personalized proposal',
      'Site visit and relationship building',
      'Flexible decision timeline',
    ],
    priority: 'medium',
    applicationsPerYear: 2,
  },
  {
    id: 43,
    name: 'ZooFund Conservation Support',
    organization: 'ZooFund Collaborative',
    orgDescription: 'Network of zoos funding conservation field projects.',
    amount: 125000,
    deadline: '2026-10-15',
    focus: 'Zoo-Supported Field Conservation',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Funding through zoo partnerships for field conservation. Emphasis on species represented in participating zoos.',
    keyRequirements: [
      'Partnership with participating zoo',
      'Field conservation focus',
      'Species represented in zoo',
      'Research and monitoring component',
    ],
    eligibility: [
      'Non-profit organizations',
      'Research institutions',
      'Community groups (with zoo partnership)',
      'International conservation organizations',
    ],
    applicationSteps: [
      'Zoo partner identification',
      'Collaborative proposal development',
      'Joint submission to fund',
      'Review period: 90 days',
    ],
    priority: 'medium',
    applicationsPerYear: 1,
  },
  {
    id: 44,
    name: 'National Endowment for the Humanities - Humanities Council',
    organization: 'National Endowment for the Humanities',
    orgDescription: 'Federal agency supporting humanities education and research.',
    amount: 150000,
    deadline: '2026-10-30',
    focus: 'Humanities & Wildlife Education',
    animalTypes: ['Reptiles', 'Mixed Species'],
    description: 'Funds humanities-based education programs with wildlife or nature themes. Story-based learning and cultural approaches.',
    keyRequirements: [
      'Humanities education component',
      'Wildlife or nature connection',
      'Cultural or storytelling element',
      'Public education focus',
    ],
    eligibility: [
      'Non-profit organizations',
      'Educational institutions',
      'Museums and cultural organizations',
      'Public broadcasting',
    ],
    applicationSteps: [
      'Proposal through NEH portal',
      'Narrative and educational plan',
      'Budget and evaluation strategy',
      'Peer review: 150+ days',
    ],
    priority: 'low',
    applicationsPerYear: 1,
  },
  {
    id: 45,
    name: 'Environmental Education Consortium Grants',
    organization: 'EEC',
    orgDescription: 'Supports environmental and outdoor education programs.',
    amount: 75000,
    deadline: '2026-09-15',
    focus: 'Environmental Education',
    animalTypes: ['Reptiles', 'Mixed Species'],
    description: 'Funds outdoor and environmental education programs. Emphasis on hands-on learning and student engagement.',
    keyRequirements: [
      'Environmental education focus',
      'Hands-on learning component',
      'Student engagement documented',
      'Community or school partnerships',
    ],
    eligibility: [
      'Non-profit organizations',
      'Schools and educational organizations',
      'Environmental centers',
      'Community education programs',
    ],
    applicationSteps: [
      'Submit education program details',
      'Student outcomes and evaluation plan',
      'Budget and timeline',
      'Decision within 60 days',
    ],
    priority: 'medium',
    applicationsPerYear: 2,
  },
  {
    id: 46,
    name: 'International Species Survival Commission Fund',
    organization: 'IUCN - SSC',
    orgDescription: 'Supports conservation of endangered species internationally.',
    amount: 200000,
    deadline: '2026-11-01',
    focus: 'Endangered Species Protection',
    animalTypes: ['Reptiles', 'Amphibians', 'Primates', 'Mixed Species'],
    description: 'Funds species recovery programs for threatened and endangered species. Global reach with emphasis on science-based approaches.',
    keyRequirements: [
      'Threatened/endangered species focus',
      'Science-based recovery plan',
      'International cooperation',
      'Research and action integration',
    ],
    eligibility: [
      'Non-profit organizations',
      'Government wildlife agencies',
      'Research institutions',
      'IUCN member organizations',
    ],
    applicationSteps: [
      'Detailed species recovery proposal',
      'Scientific documentation',
      'International partnership letters',
      'Competitive process: 120 days',
    ],
    priority: 'high',
    applicationsPerYear: 1,
  },
  {
    id: 47,
    name: 'Wildlife Rehabilitation Excellence Award',
    organization: 'Wildlife Rehabilitation Association',
    orgDescription: 'Supports wildlife rehabilitation and care facilities.',
    amount: 60000,
    deadline: '2026-08-20',
    focus: 'Wildlife Rehabilitation',
    animalTypes: ['Reptiles', 'Amphibians', 'Mixed Species'],
    description: 'Funds facility improvements and program enhancements at wildlife rehabilitation centers. Emphasis on care standards and innovation.',
    keyRequirements: [
      'Licensed wildlife rehab facility',
      'Facility improvement or program focus',
      'Care innovation component',
      'Documentation of species treated',
    ],
    eligibility: [
      'Licensed wildlife rehabilitation facilities',
      'Non-profit rehabilitation centers',
      'Zoo-based rehabilitation programs',
      'Sanctuary rehabilitation operations',
    ],
    applicationSteps: [
      'Facility information and license details',
      'Project or improvement description',
      'Budget and timeline',
      'Decision within 45 days',
    ],
    priority: 'high',
    applicationsPerYear: 1,
  },
];
